//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test_H
#define METASPRITE_test_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test_TILE_ORIGIN 0
#define test_TILE_W 8
#define test_TILE_H 8
#define test_WIDTH 160
#define test_HEIGHT 144
#define test_TILE_COUNT 28
#define test_PALETTE_COUNT 8
#define test_COLORS_PER_PALETTE 4
#define test_TOTAL_COLORS 32
#define test_MAP_ATTRIBUTES 0
extern const unsigned char test_map[360];
#define test_map_attributes test_map

BANKREF_EXTERN(test)

extern const palette_color_t test_palettes[32];
extern const uint8_t test_tiles[448];

#endif
